//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proverka020724
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Жилье.
    /// </summary>
    // *** Start programmer edit section *** (Жилье CustomAttributes)

    // *** End programmer edit section *** (Жилье CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Жилье : ICSSoft.STORMNET.DataObject
    {

        private string fРазмер;

        private string fРасположение;

        // *** Start programmer edit section *** (Жилье CustomMembers)

        // *** End programmer edit section *** (Жилье CustomMembers)


        /// <summary>
        /// Размер.
        /// </summary>
        // *** Start programmer edit section *** (Жилье.Размер CustomAttributes)

        // *** End programmer edit section *** (Жилье.Размер CustomAttributes)
        [StrLen(255)]
        public virtual string Размер
        {
            get
            {
                // *** Start programmer edit section *** (Жилье.Размер Get start)

                // *** End programmer edit section *** (Жилье.Размер Get start)
                string result = this.fРазмер;
                // *** Start programmer edit section *** (Жилье.Размер Get end)

                // *** End programmer edit section *** (Жилье.Размер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Жилье.Размер Set start)

                // *** End programmer edit section *** (Жилье.Размер Set start)
                this.fРазмер = value;
                // *** Start programmer edit section *** (Жилье.Размер Set end)

                // *** End programmer edit section *** (Жилье.Размер Set end)
            }
        }

        /// <summary>
        /// Расположение.
        /// </summary>
        // *** Start programmer edit section *** (Жилье.Расположение CustomAttributes)

        // *** End programmer edit section *** (Жилье.Расположение CustomAttributes)
        [StrLen(255)]
        public virtual string Расположение
        {
            get
            {
                // *** Start programmer edit section *** (Жилье.Расположение Get start)

                // *** End programmer edit section *** (Жилье.Расположение Get start)
                string result = this.fРасположение;
                // *** Start programmer edit section *** (Жилье.Расположение Get end)

                // *** End programmer edit section *** (Жилье.Расположение Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Жилье.Расположение Set start)

                // *** End programmer edit section *** (Жилье.Расположение Set start)
                this.fРасположение = value;
                // *** Start programmer edit section *** (Жилье.Расположение Set end)

                // *** End programmer edit section *** (Жилье.Расположение Set end)
            }
        }
    }
}

