//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proverka020724
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ЛапаКошки.
    /// </summary>
    // *** Start programmer edit section *** (ЛапаКошки CustomAttributes)

    // *** End programmer edit section *** (ЛапаКошки CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class ЛапаКошки : ICSSoft.STORMNET.DataObject
    {

        private string fРасположение;

        private bool fЦелостность;

        private IIS.Proverka020724.Кошка fКошка;

        // *** Start programmer edit section *** (ЛапаКошки CustomMembers)

        // *** End programmer edit section *** (ЛапаКошки CustomMembers)


        /// <summary>
        /// Расположение.
        /// </summary>
        // *** Start programmer edit section *** (ЛапаКошки.Расположение CustomAttributes)

        // *** End programmer edit section *** (ЛапаКошки.Расположение CustomAttributes)
        [StrLen(255)]
        public virtual string Расположение
        {
            get
            {
                // *** Start programmer edit section *** (ЛапаКошки.Расположение Get start)

                // *** End programmer edit section *** (ЛапаКошки.Расположение Get start)
                string result = this.fРасположение;
                // *** Start programmer edit section *** (ЛапаКошки.Расположение Get end)

                // *** End programmer edit section *** (ЛапаКошки.Расположение Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЛапаКошки.Расположение Set start)

                // *** End programmer edit section *** (ЛапаКошки.Расположение Set start)
                this.fРасположение = value;
                // *** Start programmer edit section *** (ЛапаКошки.Расположение Set end)

                // *** End programmer edit section *** (ЛапаКошки.Расположение Set end)
            }
        }

        /// <summary>
        /// Целостность.
        /// </summary>
        // *** Start programmer edit section *** (ЛапаКошки.Целостность CustomAttributes)

        // *** End programmer edit section *** (ЛапаКошки.Целостность CustomAttributes)
        public virtual bool Целостность
        {
            get
            {
                // *** Start programmer edit section *** (ЛапаКошки.Целостность Get start)

                // *** End programmer edit section *** (ЛапаКошки.Целостность Get start)
                bool result = this.fЦелостность;
                // *** Start programmer edit section *** (ЛапаКошки.Целостность Get end)

                // *** End programmer edit section *** (ЛапаКошки.Целостность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЛапаКошки.Целостность Set start)

                // *** End programmer edit section *** (ЛапаКошки.Целостность Set start)
                this.fЦелостность = value;
                // *** Start programmer edit section *** (ЛапаКошки.Целостность Set end)

                // *** End programmer edit section *** (ЛапаКошки.Целостность Set end)
            }
        }

        /// <summary>
        /// мастеровая ссылка на шапку IIS.Proverka020724.Кошка.
        /// </summary>
        // *** Start programmer edit section *** (ЛапаКошки.Кошка CustomAttributes)

        // *** End programmer edit section *** (ЛапаКошки.Кошка CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Кошка"})]
        public virtual IIS.Proverka020724.Кошка Кошка
        {
            get
            {
                // *** Start programmer edit section *** (ЛапаКошки.Кошка Get start)

                // *** End programmer edit section *** (ЛапаКошки.Кошка Get start)
                IIS.Proverka020724.Кошка result = this.fКошка;
                // *** Start programmer edit section *** (ЛапаКошки.Кошка Get end)

                // *** End programmer edit section *** (ЛапаКошки.Кошка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЛапаКошки.Кошка Set start)

                // *** End programmer edit section *** (ЛапаКошки.Кошка Set start)
                this.fКошка = value;
                // *** Start programmer edit section *** (ЛапаКошки.Кошка Set end)

                // *** End programmer edit section *** (ЛапаКошки.Кошка Set end)
            }
        }
    }

    /// <summary>
    /// Detail array of ЛапаКошки.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfЛапаКошки CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfЛапаКошки CustomAttributes)
    public class DetailArrayOfЛапаКошки : ICSSoft.STORMNET.DetailArray
    {

        // *** Start programmer edit section *** (IIS.Proverka020724.DetailArrayOfЛапаКошки members)

        // *** End programmer edit section *** (IIS.Proverka020724.DetailArrayOfЛапаКошки members)


        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ЛапаКошки by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ЛапаКошки.
        /// </summary>
        public DetailArrayOfЛапаКошки(IIS.Proverka020724.Кошка fКошка) : 
                base(typeof(ЛапаКошки), ((ICSSoft.STORMNET.DataObject)(fКошка)))
        {
        }

        public IIS.Proverka020724.ЛапаКошки this[int index]
        {
            get
            {
                return ((IIS.Proverka020724.ЛапаКошки)(this.ItemByIndex(index)));
            }
        }

        public virtual void Add(IIS.Proverka020724.ЛапаКошки dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}

